<h1>Sportdykning</h1>
<h2>Dykning inom Delfinen</h2>
Vi bedriver förutom ren dykverksamhet och fridykarutbildning även sportdykarutbildning. Detta sker inom de ramar som föreskrivs av Svenska Sportdykarförbundet och CMAS. CMAS är ett från början franskt utbildningssystem och grundaren av CMAS är ingen mindre än Jaques Cousteau. Systemet är uppbyggt som följer:

<h3>*CMAS (läs enstjärnigt CMAS dykcertifikat): Grundkurs i sportdykning</h3>
Efter avslutad kurs är du kvalificerad att dyka i öppet vatten till max 20 m tillsammans med dykare med minst **CMAS-certifikat (se nedan). I utbildningen ingår förutom lektioner i dykfysik, tabeller, dykmedicin och tillämpad dykning även utbildning i Hjärt-Lungräddning samt inom den praktiska delen livräddning. Grundkravet för att påbörja kursen är att man fyller minst 15 år det året kursen påbörjas, att man kan simma minst 200 m samt att man har genomgått en godkänd läkarundersökning inklusive lungröntgen.

<h3>**CMAS: Fortsättningskurs i dykning</h3>
Detta är en mestadels praktisk kurs där man lär sig grundläggande teori och praktik för lite mer avancerade dykmetoder såsom nattdyk, djupdyk, vrakdyk och vinterdyk. I utbildningen ingår praktiskt genomförande av ett antal av dessa olika dykmetoder. Förkravet till denna kurs är *CMAS eller motsvarande och minst 6 dyktimmar fördelade på minst 10 dyk. När man sedan har samlat ihop minst 15 dyktimmar får man även lov att ta hand om dykare med *CMAS certifikat.	

<h3>***CMAS: Utbildning till dykledare</h3>
Efter avslutad kurs är du kvalificerad att leda grupper med dykare i öppet vatten. Under kursens gång kommer du att få lära dig att behärska tabeller, medicin och fysik till fulländning. Dessutom kommer du att få lära dig grunderna i hur man framför en mindre båt samt inte minst hur du skall agera som dykledare i en nödsituation. I den praktiska delen skall du visa att du kan hantera dig själv och din utrustning samt att du har den nödvändiga kunskapen om nödsituationer och livräddning. Förkravet är **CMAS eller motsvarande samt minst 40 dyktimmar fördelade på minst 50 dyk. Dessutom skall man ha genomfört ett antal olika dykmetoder såsom bla djupdyk, vrakdyk, vinterdyk och båtdyk. Efter dessa utbildningar kan man vidareutbilda sig till instruktör på olika nivåer från *CMAS-instruktör till ***CMAS-instruktör.	

<h3>Utbildningar på klubbnivå</h3>
Utbildningen sker under lugna och betryggande former under ledning av erfarna och välutbildade instruktörer och inga elever släpps ur utbildningen förrän de har uppnått de krav som ställs samt att de själva känner sig redo. Efter utbildningen slussas eleverna in i den ordinarie dykverksamheten för att på ett roligt sätt skaffa sig erfarenhet genom att dyka med de som är mer vana, något som de flesta tycker är mycket positivt. 
<br /><br />
Har du några frågor angående dykutbildningen är du välkommen att fråga oss.