<h3>Välkommen till DK Delfinen</h3>
<p>
    Klubben, som har sitt säte i Helsingborg, grundades 1958/1959 och har ca hundratrettio medlemmar, både sportdykare och fridykare. Klubbdyk arrangeras varje helg från april till oktober. Aktuell dykledare spelar in på klubbens telefonsvarare, 042-211520, när och var dykning kommer att ske. Icke medlemmar kan följa med efter överenskommelse med dykledaren.
</p>
<hr>
<div class="span-6 border">
    <p>
    <h4>Dykning inom Delfinen</h4>
        Vi bedriver förutom ren dykverksamhet och fridykarutbildning även sportdykarutbildning. Detta sker inom de ramar som föreskrivs av Svenska Sportdykarförbundet och CMAS. CMAS är ett från början franskt utbildningssystem och grundaren av CMAS är ingen mindre än Jaques Cousteau.
    
    
    
</div>

    <p>
        Test test test Test test test Test test test Test test test Test test test


