<h1>Välkommen till DK Delfinen</h1>
<p>
Klubben, som har sitt säte i Helsingborg, grundades 1958/1959 och har ca hundratrettio medlemmar, både sportdykare och fridykare. Klubbdyk arrangeras varje helg från april till oktober. Aktuell dykledare spelar in på klubbens telefonsvarare, 042-211520, när och var dykning kommer att ske. Icke medlemmar kan följa med efter överenskommelse med dykledaren.<br />
<br />
Dykning sker mestadels vid Kullaberg men det sker även i mer avlägsna vatten. Man kan läsa om DK Delfinens historia i klubbtidningen "Tumlaren". Tumlaren är också namnet som använts på klubbens båtar. Nuvarande båt heter Tumlaren V och köptes in vintern 1998/1999. Båten kan utan problem ta med 10 dykare med utrustning.
</p>

<h2>Dykning inom Delfinen</h2>
<p>
Vi bedriver förutom ren dykverksamhet och fridykarutbildning även sportdykarutbildning. Detta sker inom de ramar som föreskrivs av Svenska Sportdykarförbundet och CMAS. CMAS är ett från början franskt utbildningssystem och grundaren av CMAS är ingen mindre än Jaques Cousteau.
</p>

<div id="events">
	<?php echo $this->layout()->events; ?>
</div>

<div id="news">
	<?php echo $this->layout()->news; ?>
</div>
<div id="thumbnails">
	<?php echo $this->layout()->thumbnails; ?>
</div>