<h1>Bli medlem</h1>
<p>
Vill du bli medlem i Dykarklubben Delfinen tar du kontakt med vår kassör (kassor@dkdelfinen.se).<br />
<br />
<table border="0" width="30%" cellpadding="0" cellspacing="0">
<tr>
	<th colspan="2" align="left">Kostnad per år:</th>
</tr>
<tr>
	<td>Senior</td>
	<td>600 kronor</td>
</tr>
<tr>
	<td>Familje Senior</td>
	<td>450 kronor</td>
</tr>
<tr>
	<td>Juniorer</td>
	<td>150 kronor</td>
</tr>
<tr>
	<td>Intressemedlemskap</td>
	<td>100 kronor</td>
</tr>
</table>
<br />
Inbetalningar görs på PG nr 519631-6. Ange följande information vid inbetalningen:<br />
Förnamn, Efternamn<br />
Adress<br />
Email<br />
Telefon och<br />
Personnummer (ÅÅMMDD-XXXX).<br />
<br />
Medlemskapet löper mellan 1/10 - 30/9.
</p>