<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/css/slimbox2.css" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/css/pwi.css" type="text/css" media="screen" />
<script type="application/javascript" src="<?php echo $this->baseUrl()?>/js/slimbox2.js"></script>
<script type="application/javascript" src="<?php echo $this->baseUrl()?>/js/jquery.EmbedPicasaGallery.js"></script>
<script type="application/javascript" src="<?php echo $this->baseUrl()?>/js/jquery.pwi.js"></script>
<script type="application/javascript" src="<?php echo $this->baseUrl()?>/js/jquery.blockUI.js"></script>

<script type="text/javascript">
/*$(document).ready(function() {

        var options = {
                username: 'dykklubben.delfinen',
                mode: "<?php echo $this->viewMode;?>",
                album: "<?php echo $this->albumId;?>",
                thumbSize: 144,
                thumbCss: { margin: '5px' },
                labels: {photo:"bild", //-- override labels, to translate into your required language
                                photos: "bilder",
                                albums: "Tillbaka till album",
                                slideshow: "Visa bildspel",
                                loading: "Läser in bilder...",
                                page: "Sida",
                                prev: "Föregående",
                                next: "Nästa",
                                devider: "|"
                }
                
        };

        $("#mygallery").pwi(options);

});*/


jQuery(document).ready(function() {

jQuery("#mygallery").EmbedPicasaGallery('dykklubben.delfinen',{
  matcher:    /./,  // string or regexp matching album title
  size:      '144',  // thumb size (32,48,64,72,144,160))
  msg_loading_list :  'Laddar bilder',
  msg_back :   'Tillbaka',
  albumid : '<?php echo $this->albumId;?>',
  loading_animation: '/delfinen/public/css/loading.gif',
  thumb_tuner:        function($div,item,i){var desc = item.media$group.media$description.$t; if (desc) $div.append('<br>' + desc)}
});
});


</script>
<div id="mygallery"></div>
