<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/new-site.css'); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery.js'); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery.EmbedPicasaGallery.js'); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/slimbox2.js'); ?>
                
    </head>
    <body>

        <div id="container">

            <div id="header" class="shadow"></div>
            
            <div id="navigation" class="shadow">
            	<?php echo $this->navigation()->menu(); ?>
            </div>

            <div id="content" class="shadow">
                    <?php echo $this->layout()->content; ?>          		
            </div>
            
            <div id="footer">
            <ul>
            	<li><img src="<?php echo $this->baseUrl().'/images/sponsor_cityfarg.gif'?>" alt="Cityfärg"></li>
            	<li><img src="<?php echo $this->baseUrl().'/images/sponsor_elbe.gif'?>" alt="ELBE"></li>
            	<li><img src="<?php echo $this->baseUrl().'/images/sponsor_termokyl.gif'?>" alt="Termokyl"></li>
            </ul>
            </div>
        </div>

    </body>
</html>